// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "@/components/ui/sonner";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Pizzerianovellus",
//   description: "Generated by DotSkills",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//         <Toaster richColors position="top-center" />
//       </body>
//     </html>
//   );
// }


// -------------------------------------

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pizzerianovellus – Delicious Pizza Ordering App",
  description: "Order your favorite pizzas online quickly and easily with Pizzerianovellus. Fresh, hot, and delivered to your doorstep.",
  keywords: ["pizza", "online pizza order", "food delivery", "Pizzerianovellus", "fast food"],
  authors: [{ name: "DotSkills", url: "https://dotskillsbd.com" }],
  creator: "DotSkills",
  publisher: "DotSkills",
  openGraph: {
    title: "Pizzerianovellus – Delicious Pizza Ordering App",
    description: "Order your favorite pizzas online quickly and easily with Pizzerianovellus.",
    url: "https://pizzerianovellus.com",
    siteName: "Pizzerianovellus",
    locale: "en_US",
    type: "website",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}